---
title: "SPICe statistics"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
source("../R/functions/f_make_charts.R")

date <- paste(lubridate::day(Sys.Date()),
              month.name[lubridate::month(Sys.Date())], 
              lubridate::year(Sys.Date()))

```

## Sidebar {.sidebar}

Explore statistics by topic, Scottish Parliament region, or compare statistics across UK nations.

Page last updated on `r date`.

## Col 1 - by region

####  **BY REGION**

### Statistics

```{r}
flexdashboard::valueBox("Central Scotland", icon = "ion-stats-bars", 
                        color = spcols[8], href = "central_scotland.html")
```

### Statistics

```{r}
flexdashboard::valueBox("Glasgow", icon = "ion-stats-bars", color = spcols[8],
                        href = "glasgow.html")
```

### Statistics

```{r}
flexdashboard::valueBox("Highlands & Islands", color = spcols[8], 
                        icon = "ion-stats-bars",
                        href = "highlands_and_islands.html")
```

### Statistics

```{r}
flexdashboard::valueBox("Lothian", color = spcols[8], icon = "ion-stats-bars",
                        href = "lothian.html")
```

## Col 2 - by region

####  **BY REGION**

### Statistics

```{r}
flexdashboard::valueBox("Mid Scotland & Fife", color = spcols[8],
         icon = "ion-stats-bars", href = "mid_scotland_and_fife.html")
```

### Statistics

```{r}
flexdashboard::valueBox("North East Scotland", color = spcols[8],
         icon = "ion-stats-bars", href = "north_east_scotland.html")
```

### Statistics

```{r}
flexdashboard::valueBox("South Scotland", color = spcols[8],
         icon = "ion-stats-bars", href = "south_scotland.html")
```

### Statistics

```{r}
flexdashboard::valueBox("West Scotland", color = spcols[8],
         icon = "ion-stats-bars", href = "west_scotland.html")
```

## Col 2 - by topic

#### **BY TOPIC**

### Ethnicity

```{r}
flexdashboard::valueBox("Ethnicity",
         color = spcols[12],
         icon = "ion-android-train",
         href = "ethnic.html")
```

### Gaelic / Scots language

```{r}
flexdashboard::valueBox("Gaelic / Scots language",
         color = spcols[12],
         icon = "ion-card",
         href = "gaelic.html")
```
