---
title: "`r params$region`"
params:
  region: Central Scotland
---
  
```{r setup, include = FALSE}

knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

```

```{r prep_data}

library(highcharter)
x <- params$region

```

```{r ethnicity}

# Ethnicity

maps_ethnic <- readRDS("data/ethnic_maps.rds")

# add layout and charts by looping through regions
title1 <- "# Ethnicity"
sidebar1 <- paste0("## Sidebar {.sidebar}\n",
                  knitr::knit_expand("dashboard/_sidebar_text/ethnic_text.Rmd"))
layout1 <- knitr::knit_expand('dashboard/_layouts/ethnic_layout.Rmd')

title1 = knitr::knit_child(text = unlist(title1), quiet = TRUE)
sidebar1 <- knitr::knit_child(text = unlist(sidebar1), quiet = TRUE)
layout1 = knitr::knit_child(text = unlist(layout1), quiet = TRUE)

```

```{r gaelic}

# Gaelic / Scots language

maps_gaelic <- readRDS("data/gaelicscots_maps.rds")

# add layout and charts by looping through regions
title2 <- "# Gaelic & Scots"
sidebar2 <- paste0("## Sidebar {.sidebar}\n",
                  knitr::knit_expand("dashboard/_sidebar_text/gaelic_text.Rmd"))
layout2 <- knitr::knit_expand('dashboard/_layouts/gaelic_layout.Rmd')

title2 = knitr::knit_child(text = unlist(title2), quiet = TRUE)
sidebar2 <- knitr::knit_child(text = unlist(sidebar2), quiet = TRUE)
layout2 = knitr::knit_child(text = unlist(layout2), quiet = TRUE)

```


```{r output, results='asis'}

cat(title1, sidebar1, layout1,
    title2, sidebar2, layout2, 
    # title3, sidebar3, layout3, 
    # title4, sidebar4, layout4, 
    # title5, sidebar5, layout5, 
    sep = '\n')

```


